################################# Default configuration ###################
# provide your domain here
baseURL = "https://hallobitcoin.github.io/"
# The directory to where Hugo will write the final static site.
publishDir = "docs"
# theme
theme = "dot"
# site title
title = "Hallo Bitcoin."
# disable language
# disableLanguages = ["En"]
# set default language
defaultContentLanguage = "de"
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)
# unsafe html
[markup.goldmark.renderer]
unsafe = true


############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# customize color
primary_color = "#02007e"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


############################## social links ##############################
[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "https://twitter.com/bitcoin"
  
[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
link = "https://github.com/hallobitcoin"

################################ German Language ######################
[Languages.de]
languageName = "De"
languageCode = "de-at"
weight = 2
copyright = "Copyright © 2021 by [Hallo Bitcoin](https://hallobitcoin.github.io/)"

# banner
[Languages.de.params.banner]
title = "Bitcoin Support Center"
subtitle = "Einfache und verständliche Antworten auf Deine Fragen zum Thema Bitcoin"
bg_image = "images/banner.jpg"
placeholder = "Du hast eine Frage? Stell sie hier!"

# call to action
[Languages.de.params.cta]
enable = true
title = "Du hast keine Antwort auf Deine Frage gefunden?"
content = "Schreib uns eine Mail an hallo@example.com und wir beantworten sie Dir direkt!"
# call to action button
[Languages.de.params.cta.button]
enable = true
label = "Jetzt kontaktieren!"
link = "contact"


################## german navigation #################
[[Languages.de.menu.main]]
name = "Home"
url = "/"
weight = 1

[[Languages.de.menu.main]]
name = "FAQ"
url = "faq"
weight = 2

[[Languages.de.menu.main]]

# Dropdown menu
[[Languages.de.menu.main]]
weight = 4
name = "Mehr"
hasChildren = true

  [[Languages.de.menu.main]]
  parent = "Mehr"
  name = "Ressourcen"
  url = "resources"
  weight = 2

